const AppConstants = {
  categories: [
    ".io",
    "Action",
    "Adventure",
    "Beauty",
    "Casual",
    "Clicker",
    "Driving",
    "Puzzle",
    "Shotting",
    "Sports",
  ],

  tags: [
    "1 Player",
    "2 Player",
    "2D",
    "3 Player",
    "3D",
    "Airplane",
    "Alien",
    "Animal",
    "Acrade",
    "Archery",
    "Arena",
    "Avoid",
    "Baby",
    "Ball",
    "Basketball",
    "Battle",
    "Battleship",
    "Bike",
    "BMX",
    "Boat",
    "Bomberman",
    "Boxing",
    "Brain",
    "Building",
    "Business",
    "Car",
    "Cartoon",
    "Cat",
    "Chess",
    "Chrismas",
    "Classic",
    "Collect",
    "Color",
    "Coloring",
    "Connect",
    "Controller",
    "Cooking",
    "Cricket",
    "Crossword",
    "Defense",
    "Destroy",
    "Detective",
    "Difficult",
    "Dinosaur",
    "Dog",
    "Dragon",
    "Dress up",
    "Drifting",
    "Escape",
    "Farming",
    "Fashion",
    "Fighting",
    "Fishing",
    "Food",
    "Football",
    "FPS",
    "Grow",
    "Gun",
    "Helicopter",
    "Hero",
    "Horde Survival",
    "Horror",
    "Idle",
    "Incremental",
    "Jumping",
    "Killing",
    "Logic",
    "Mafia",
    "Magic",
    "Managment",
    "...",
  ],

  gameTypes: [
    "Unity 2024",
    "Unity 2023",
    "Unity 2022",
    "Unity 2021",
    "Unity 2020",
    "Unity 2019",
    "Unity 2018",
    "Unity 2017",
    "Unity 5.6",
    "Unity 5.5",
    "Unity 5.4",
    "IFrame",
    "HTML 5",
  ],

  // unityConfig: {
  //   loaderUrl: "Build/Public.loader.js",
  //   dataUrl: "Build/Public.data.gz",
  //   frameworkUrl: "Build/Public.framework.js.gz",
  //   codeUrl: "Build/Public.wasm.gz",
  // },

  unityConfig: {
    loaderUrl: "Build/public.loader.js",
    dataUrl: "Build/public.data",
    frameworkUrl: "Build/public.framework.js",
    codeUrl: "Build/public.wasm",
  },

  cardData: [
    {
      _id: "0",
      // imageOut: "/images/cardImages/0.jpeg",
      imageOut: "/images/initialCardImages/0.jpeg",

      imageOver: "/images/cardImages/6.jpeg",
      imageCardOver: "/images/initialCardImages/6.jpeg",
    },
    {
      _id: "1",
      // imageOut: "/images/cardImages/1.jpeg",
      imageOut: "/images/initialCardImages/1.jpeg",

      imageOver: "/images/cardImages/7.jpeg",
      imageCardOver: "/images/initialCardImages/7.jpeg",
    },
    {
      _id: "2",
      // imageOut: "/images/cardImages/2.jpeg",
      imageOut: "/images/initialCardImages/2.jpeg",

      imageOver: "/images/cardImages/8.jpeg",
      imageCardOver: "/images/initialCardImages/8.jpeg",
    },
    {
      _id: "3",
      // imageOut: "/images/cardImages/3.jpeg",
      imageOut: "/images/initialCardImages/3.jpeg",

      imageOver: "/images/cardImages/9.jpeg",
      imageCardOver: "/images/initialCardImages/9.jpeg",
    },
    {
      _id: "4",
      // imageOut: "/images/cardImages/4.jpeg",
      imageOut: "/images/initialCardImages/4.jpeg",

      imageOver: "/images/cardImages/0.jpeg",
      imageCardOver: "/images/initialCardImages/0.jpeg",
    },
    {
      _id: "5",
      // imageOut: "/images/cardImages/8.jpeg",
      imageOut: "/images/initialCardImages/8.jpeg",

      imageOver: "/images/cardImages/4.jpeg",
      imageCardOver: "/images/initialCardImages/4.jpeg",
    },
    {
      _id: "6",
      // imageOut: "/images/cardImages/6.jpeg",
      imageOut: "/images/initialCardImages/6.jpeg",

      imageOver: "/images/cardImages/2.jpeg",
      imageCardOver: "/images/initialCardImages/2.jpeg",
    },
    {
      _id: "7",
      // imageOut: "/images/cardImages/7.jpeg",
      imageOut: "/images/initialCardImages/7.jpeg",

      imageOver: "/images/cardImages/3.jpeg",
      imageCardOver: "/images/initialCardImages/3.jpeg",
    },
    {
      _id: "8",
      // imageOut: "/images/cardImages/5.jpeg",
      imageOut: "/images/initialCardImages/5.jpeg",

      imageOver: "/images/cardImages/1.jpeg",
      imageCardOver: "/images/initialCardImages/1.jpeg",
    },
    {
      _id: "9",
      // imageOut: "/images/cardImages/9.jpeg",
      imageOut: "/images/initialCardImages/9.jpeg",

      imageOver: "/images/cardImages/5.jpeg",
      imageCardOver: "/images/initialCardImages/5.jpeg",
    },
  ],
};

export default AppConstants;
